/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.archivonegativoscronica;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author francisco.ortiz
 */
public class MapaAreas {
    
    private PreparedStatement stmt ;
    private final Connection conn ;
    private boolean resultado ;
    
    public MapaAreas(Connection con) throws SQLException {
        this.conn = con ;
        conn.setAutoCommit(false);
        List<String[]> mapa = listaParaCargar();
        stmt = conn.prepareStatement("INSERT INTO mapaAreas (cod,ingles,espaniol) "
                + "VALUES (?,?,?);");
        mapa.forEach((area) -> {
            try {
                String cod = "" ;
                switch(area[0].length()){
                    case 1:
                        cod = area[0] + "------" ;
                        break;
                    case 2:
                        cod = area[0] + "-----" ;
                        break;
                    case 3:
                        cod = area[0] + "----" ;
                        break;
                    case 4:
                        cod = area[0] + "---" ;
                        break;
                    case 5:
                        cod = area[0] + "--" ;
                        break;
                    case 6:
                        cod = area[0] + "-" ;
                        break;
                    case 7:
                        cod = area[0] ;
                        break;
                }
                stmt.setString(1,cod);
                stmt.setString(2,area[1]);
                stmt.setString(3,area[2]);
                stmt.addBatch();                        
                stmt.clearParameters();
            } catch (SQLException ex) {
                System.out.print("SQLException: " + ex.getMessage() + "\n" +
                            "SQLState: " + ex.getSQLState()+ "\n" +
                            "VendorError: " + ex.getErrorCode());
            }
        });
        
        try {
            int [] results = stmt.executeBatch();
            conn.commit();
            resultado = true ;
        } catch (SQLException ex) {
            System.out.print("SQLException: " + ex.getMessage() + "\n" +
                            "SQLState: " + ex.getSQLState()+ "\n" +
                            "VendorError: " + ex.getErrorCode());
            resultado = false ;
        }
        
    }
    
    public boolean resultado() {
        return resultado ;
    }
    
    private List<String[]> listaParaCargar() {
        List<String[]> areas = new ArrayList<>() ;        
        areas.add("a|Asia|Asia".split("\\|")) ;
        areas.add("a-af|Afghanistan|Afganistán".split("\\|")) ;
        areas.add("a-ai|Armenia (Republic)|Armenia".split("\\|")) ;
        areas.add("a-aj|Azerbaijan|Azerbaiyán".split("\\|")) ;
        areas.add("a-ba|Bahrain|Bahrein".split("\\|")) ;
        areas.add("a-bg|Bangladesh|Bangladesh".split("\\|")) ;
        areas.add("a-bn|Borneo|Borneo".split("\\|")) ;
        areas.add("a-br|Burma|Birmania".split("\\|")) ;
        areas.add("a-bt|Bhutan|Bután".split("\\|")) ;
        areas.add("a-bx|Brunei|Brunei".split("\\|")) ;
        areas.add("a-cb|Cambodia|Camboya".split("\\|")) ;
        areas.add("a-cc|China|China".split("\\|")) ;
        areas.add("a-cc-an|Anhui Sheng (China)|Anhui Sheng (China)".split("\\|")) ;
        areas.add("a-cc-ch|Zhejiang Sheng (China)|Zhejiang Sheng (China)".split("\\|")) ;
        areas.add("a-cc-cq|Chongqing (China)|Chongqing (China)".split("\\|")) ;
        areas.add("a-cc-fu|Fujian Sheng (China)|Fujian Sheng (China)".split("\\|")) ;
        areas.add("a-cc-ha|Hainan Sheng (China)|Hainan Sheng (China)".split("\\|")) ;
        areas.add("a-cc-he|Heilongjiang Sheng (China)|Heilongjiang Sheng (China)".split("\\|")) ;
        areas.add("a-cc-hh|Hubei Sheng (China)|Hubei Sheng (China)".split("\\|")) ;
        areas.add("a-cc-hk|Hong Kong (China)|Hong Kong, (China)".split("\\|")) ;
        areas.add("a-cc-ho|Henan Sheng (China)|Henan Sheng (China)".split("\\|")) ;
        areas.add("a-cc-hp|Hebei Sheng (China)|Hebei Sheng (China)".split("\\|")) ;
        areas.add("a-cc-hu|Hunan Sheng (China)|Hunan Sheng (China)".split("\\|")) ;
        areas.add("a-cc-im|Inner Mongolia (China)|Mongolia Interior (China)".split("\\|")) ;
        areas.add("a-cc-ka|Gansu Sheng (China)|Gansu Sheng (China)".split("\\|")) ;
        areas.add("a-cc-kc|Guangxi Zhuangzu Zizhiqu (China)|Guangxi Zhuangzu Zizhiqu (China)".split("\\|")) ;
        areas.add("a-cc-ki|Jiangxi Sheng (China)|Jiangxi Sheng (China)".split("\\|")) ;
        areas.add("a-cc-kn|Guangdong Sheng (China)|Guangdong Sheng (China)".split("\\|")) ;
        areas.add("a-cc-kr|Jilin Sheng (China)|Jilin Sheng (China)".split("\\|")) ;
        areas.add("a-cc-ku|Jiangsu Sheng (China)|Jiangsu Sheng (China)".split("\\|")) ;
        areas.add("a-cc-kw|Guizhou Sheng (China)|Guizhou Sheng (China)".split("\\|")) ;
        areas.add("a-cc-lp|Liaoning Sheng (China)|Liaoning Sheng (China)".split("\\|")) ;
        areas.add("a-cc-mh|Macau (China : Special Administrative Region)|Macao (China: Región Administrativa Especial)".split("\\|")) ;
        areas.add("a-cc-nn|Ningxia Huizu Zizhiqu (China)|Ningxia Huizu Zizhiqu (China)".split("\\|")) ;
        areas.add("a-cc-pe|Beijing (China)|Beijing (China)".split("\\|")) ;
        areas.add("a-cc-sh|Shanxi Sheng (China)|Shanxi Sheng (China)".split("\\|")) ;
        areas.add("a-cc-sm|Shanghai (China)|Shanghai (China)".split("\\|")) ;
        areas.add("a-cc-sp|Shandong Sheng (China)|Shandong Sheng (China)".split("\\|")) ;
        areas.add("a-cc-ss|Shaanxi Sheng (China)|Shaanxi Sheng (China)".split("\\|")) ;
        areas.add("a-cc-su|Xinjiang Uygur Zizhiqu (China)|Xinjiang Uygur Zizhiqu (China)".split("\\|")) ;
        areas.add("a-cc-sz|Sichuan Sheng (China)|Sichuan Sheng (China)".split("\\|")) ;
        areas.add("a-cc-ti|Tibet (China)|Tibet (China)".split("\\|")) ;
        areas.add("a-cc-tn|Tianjin (China)|Tianjin (China)".split("\\|")) ;
        areas.add("a-cc-ts|Qinghai Sheng (China)|Qinghai Sheng (China)".split("\\|")) ;
        areas.add("a-cc-yu|Yunnan Sheng (China)|Yunnan Sheng (China)".split("\\|")) ;
        areas.add("a-ccg|Yangtze River (China)|Río Yangtze (China)".split("\\|")) ;
        areas.add("a-cck|Kunlun Mountains (China and India)|Montañas Kunlun (China e India)".split("\\|")) ;
        areas.add("a-ccp|Bo Hai (China)|Bo Hai (China)".split("\\|")) ;
        areas.add("a-ccs|Xi River (China)|Río Xi (China)".split("\\|")) ;
        areas.add("a-ccy|Yellow River (China)|Río Amarillo (China)".split("\\|")) ;
        areas.add("a-ce|Sri Lanka|Sri Lanka".split("\\|")) ;
        areas.add("a-ch|Taiwan|Taiwán".split("\\|")) ;
        areas.add("a-cy|Cyprus|Chipre".split("\\|")) ;
        areas.add("a-em|Timor-Leste|Timor-Leste".split("\\|")) ;
        areas.add("a-gs|Georgia (Republic)|Georgia".split("\\|")) ;
        areas.add("a-ii|India|India".split("\\|")) ;
        areas.add("a-io|Indonesia|Indonesia".split("\\|")) ;
        areas.add("a-iq|Iraq|Irak".split("\\|")) ;
        areas.add("a-ir|Iran|Irán".split("\\|")) ;
        areas.add("a-is|Israel|Israel".split("\\|")) ;
        areas.add("a-ja|Japan|Japón".split("\\|")) ;
        areas.add("a-jo|Jordan|Jordán".split("\\|")) ;
        areas.add("a-kg|Kyrgyzstan|Kirguistán".split("\\|")) ;
        areas.add("a-kn|Korea (North)|Corea del Norte".split("\\|")) ;
        areas.add("a-ko|Korea (South)|Corea del Sur".split("\\|")) ;
        areas.add("a-kr|Korea|Corea".split("\\|")) ;
        areas.add("a-ku|Kuwait|Kuwait".split("\\|")) ;
        areas.add("a-kz|Kazakhstan|Kazajstán".split("\\|")) ;
        areas.add("a-le|Lebanon|Líbano".split("\\|")) ;
        areas.add("a-ls|Laos|Laos".split("\\|")) ;
        areas.add("a-mk|Oman|Omán".split("\\|")) ;
        areas.add("a-mp|Mongolia|Mongolia".split("\\|")) ;
        areas.add("a-my|Malaysia|Malasia".split("\\|")) ;
        areas.add("a-np|Nepal|Nepal".split("\\|")) ;
        areas.add("a-nw|New Guinea|Nueva Guinea".split("\\|")) ;
        areas.add("a-ph|Philippines|Filipinas".split("\\|")) ;
        areas.add("a-pk|Pakistan|Pakistán".split("\\|")) ;
        areas.add("a-pp|Papua New Guinea|Papúa Nueva Guinea".split("\\|")) ;
        areas.add("a-qa|Qatar|Katar".split("\\|")) ;
        areas.add("a-si|Singapore|Singapur".split("\\|")) ;
        areas.add("a-su|Saudi Arabia|Arabia Saudita".split("\\|")) ;
        areas.add("a-sy|Syria|Siria".split("\\|")) ;
        areas.add("a-ta|Tajikistan|Tayikistán".split("\\|")) ;
        areas.add("a-th|Thailand|Tailandia".split("\\|")) ;
        areas.add("a-tk|Turkmenistan|Turkmenistán".split("\\|")) ;
        areas.add("a-ts|United Arab Emirates|Emiratos Árabes Unidos".split("\\|")) ;
        areas.add("a-tu|Turkey|Turquía".split("\\|")) ;
        areas.add("a-uz|Uzbekistan|Uzbekistán".split("\\|")) ;
        areas.add("a-vt|Vietnam|Vietnam".split("\\|")) ;
        areas.add("a-ye|Yemen (Republic)|Yemen (República)".split("\\|")) ;
        areas.add("aa|Amur River (China and Russia)|Río Amur (China y Rusia)".split("\\|")) ;
        areas.add("ab|Bengal, Bay of|Bengala, bahía de".split("\\|")) ;
        areas.add("ac|Asia, Central|Asia central".split("\\|")) ;
        areas.add("ae|East Asia|Asia del Este".split("\\|")) ;
        areas.add("af|Thailand, Gulf of|Tailandia, golfo de".split("\\|")) ;
        areas.add("ag|Mekong River|Río Mekong".split("\\|")) ;
        areas.add("ah|Himalaya Mountains|Montañas del Himalaya".split("\\|")) ;
        areas.add("ai|Indochina|Indochina".split("\\|")) ;
        areas.add("ak|Caspian Sea|Mar Caspio".split("\\|")) ;
        areas.add("am|Malaya|Malaya".split("\\|")) ;
        areas.add("an|East China Sea|Mar de e China (Este)".split("\\|")) ;
        areas.add("ao|South China Sea|Mar de e China (Sur)".split("\\|")) ;
        areas.add("aopf|Paracel Islands|Islas Paracel".split("\\|")) ;
        areas.add("aoxp|Spratly Islands|Islas Spratly".split("\\|")) ;
        areas.add("ap|Persian Gulf|Golfo pérsico".split("\\|")) ;
        areas.add("ar|Arabian Peninsula|Península Arabica".split("\\|")) ;
        areas.add("as|Southeast Asia|Sudeste asiático".split("\\|")) ;
        areas.add("at|Tien Shan|Tien Shan".split("\\|")) ;
        areas.add("au|Arabian Sea|Mar Arabe".split("\\|")) ;
        areas.add("aw|Middle East|Medio Oriente".split("\\|")) ;
        areas.add("awba|West Bank|Banco Oeste".split("\\|")) ;
        areas.add("awgz|Gaza Strip|Franja de Gaza".split("\\|")) ;
        areas.add("ay|Yellow Sea|Mar Amarillo".split("\\|")) ;
        areas.add("az|South Asia|Asia del Sur".split("\\|")) ;
        areas.add("b|Commonwealth countries|Países de la Commonwealth".split("\\|")) ;
        areas.add("c|Intercontinental areas (Western Hemisphere)|Áreas intercontinentales (hemisferio occidental)".split("\\|")) ;
        areas.add("cc|Caribbean Area; Caribbean Sea|Área del Caribe; Mar Caribe".split("\\|")) ;
        areas.add("cl|Latin America|America latina".split("\\|")) ;
        areas.add("d|Developing countries|Países en desarrollo".split("\\|")) ;
        areas.add("dd|Developed countries|Países desarrollados".split("\\|")) ;
        areas.add("e|Europe|Europa".split("\\|")) ;
        areas.add("e-aa|Albania|Albania".split("\\|")) ;
        areas.add("e-an|Andorra|Andorra".split("\\|")) ;
        areas.add("e-au|Austria|Austria".split("\\|")) ;
        areas.add("e-be|Belgium|Bélgica".split("\\|")) ;
        areas.add("e-bn|Bosnia and Herzegovina|Bosnia y Herzegovina".split("\\|")) ;
        areas.add("e-bu|Bulgaria|Bulgaria".split("\\|")) ;
        areas.add("e-bw|Belarus|Bielorrusia".split("\\|")) ;
        areas.add("e-ci|Croatia|Croacia".split("\\|")) ;
        areas.add("e-cs|Czechoslovakia|Checoslovaquia".split("\\|")) ;
        areas.add("e-dk|Denmark|Dinamarca".split("\\|")) ;
        areas.add("e-er|Estonia|Estonia".split("\\|")) ;
        areas.add("e-fi|Finland|Finlandia".split("\\|")) ;
        areas.add("e-fr|France|Francia".split("\\|")) ;
        areas.add("e-ge|Germany (East)|Alemania del Este".split("\\|")) ;
        areas.add("e-gg|Guernsey|Guernsey".split("\\|")) ;
        areas.add("e-gi|Gibraltar|Gibraltar".split("\\|")) ;
        areas.add("e-gr|Greece|Grecia".split("\\|")) ;
        areas.add("e-gw|Germany (West)|Alemania del Oeste".split("\\|")) ;
        areas.add("e-gx|Germany|Alemania".split("\\|")) ;
        areas.add("e-hu|Hungary|Hungría".split("\\|")) ;
        areas.add("e-ic|Iceland|Islandia".split("\\|")) ;
        areas.add("e-ie|Ireland|Irlanda".split("\\|")) ;
        areas.add("e-im|Isle of Man|Isla de Man".split("\\|")) ;
        areas.add("e-it|Italy|Italia".split("\\|")) ;
        areas.add("e-je|Jersey|Jersey".split("\\|")) ;
        areas.add("e-kv|Kosovo|Kosovo".split("\\|")) ;
        areas.add("e-lh|Liechtenstein|Liechtenstein".split("\\|")) ;
        areas.add("e-li|Lithuania|Lituania".split("\\|")) ;
        areas.add("e-lu|Luxembourg|Luxemburgo".split("\\|")) ;
        areas.add("e-lv|Latvia|Letonia".split("\\|")) ;
        areas.add("e-mc|Monaco|Mónaco".split("\\|")) ;
        areas.add("e-mm|Malta|Malta".split("\\|")) ;
        areas.add("e-mo|Montenegro|Montenegro".split("\\|")) ;
        areas.add("e-mv|Moldova|Moldavia".split("\\|")) ;
        areas.add("e-ne|Netherlands|Países Bajos".split("\\|")) ;
        areas.add("e-no|Norway|Noruega".split("\\|")) ;
        areas.add("e-pl|Poland|Polonia".split("\\|")) ;
        areas.add("e-po|Portugal|Portugal".split("\\|")) ;
        areas.add("e-rb|Serbia|Serbia".split("\\|")) ;
        areas.add("e-rm|Romania|Rumania".split("\\|")) ;
        areas.add("e-ru|Russia (Federation)|Rusia (Federación)".split("\\|")) ;
        areas.add("e-sm|San Marino|San Marino".split("\\|")) ;
        areas.add("e-sp|Spain|España".split("\\|")) ;
        areas.add("e-sw|Sweden|Suecia".split("\\|")) ;
        areas.add("e-sz|Switzerland|Suiza".split("\\|")) ;
        areas.add("e-uk|Great Britain|Gran Bretaña".split("\\|")) ;
        areas.add("e-uk-en|England|Inglaterra".split("\\|")) ;
        areas.add("e-uk-ni|Northern Ireland|Irlanda del Norte".split("\\|")) ;
        areas.add("e-uk-st|Scotland|Escocia".split("\\|")) ;
        areas.add("e-uk-wl|Wales|Gales".split("\\|")) ;
        areas.add("e-un|Ukraine|Ucrania".split("\\|")) ;
        areas.add("e-ur|Russia. Russian Empire. Soviet Union. Former Soviet Republics|Rusia. Imperio ruso. Unión Soviética. Ex repúblicas soviéticas".split("\\|")) ;
        areas.add("e-urc|Central Chernozem Region (Russia)|Región de Chernozem Central (Rusia)".split("\\|")) ;
        areas.add("e-ure|Siberia, Eastern (Russia)|Siberia, Este (Rusia)".split("\\|")) ;
        areas.add("e-urf|Russian Far East (Russia)|Extremo Oriente ruso (Rusia)".split("\\|")) ;
        areas.add("e-urk|Caucasus|Cáucaso".split("\\|")) ;
        areas.add("e-urn|Soviet Union, Northwestern|Unión Soviética, Noroeste".split("\\|")) ;
        areas.add("e-urp|Volga River (Russia)|Río Volga (Rusia)".split("\\|")) ;
        areas.add("e-urr|Caucasus, Northern (Russia)|Cáucaso, Norte (Rusia)".split("\\|")) ;
        areas.add("e-urs|Siberia (Russia)|Siberia (Rusia)".split("\\|")) ;
        areas.add("e-uru|Ural Mountains (Russia)|Montes Urales (Rusia)".split("\\|")) ;
        areas.add("e-urw|Siberia, Western (Russia)|Siberia, Oeste (Rusia)".split("\\|")) ;
        areas.add("e-vc|Vatican City|Ciudad del Vaticano".split("\\|")) ;
        areas.add("e-xn|North Macedonia|Macedonia del norte".split("\\|")) ;
        areas.add("e-xo|Slovakia|Eslovaquia".split("\\|")) ;
        areas.add("e-xr|Czech Republic|Republica checa".split("\\|")) ;
        areas.add("e-xv|Slovenia|Eslovenia".split("\\|")) ;
        areas.add("e-yu|Serbia and Montenegro; Yugoslavia|Serbia y Montenegro; Yugoslavia".split("\\|")) ;
        areas.add("ea|Alps|Alpes".split("\\|")) ;
        areas.add("eb|Baltic States|Estados bálticos".split("\\|")) ;
        areas.add("ec|Europe, Central|Europa central".split("\\|")) ;
        areas.add("ed|Balkan Peninsula|Península de los Balcanes".split("\\|")) ;
        areas.add("ee|Europe, Eastern|Europa oriental".split("\\|")) ;
        areas.add("el|Benelux countries|Países del Benelux".split("\\|")) ;
        areas.add("en|Europe, Northern|Europa del norte".split("\\|")) ;
        areas.add("eo|Danube River|Rio Danubio".split("\\|")) ;
        areas.add("ep|Pyrenees|Pirineos".split("\\|")) ;
        areas.add("er|Rhine River|Río Rin".split("\\|")) ;
        areas.add("es|Europe, Southern|Europa del sur".split("\\|")) ;
        areas.add("ev|Scandinavia|Escandinavia".split("\\|")) ;
        areas.add("ew|Europe, Western|Europa occidental".split("\\|")) ;
        areas.add("f|Africa|África".split("\\|")) ;
        areas.add("f-ae|Algeria|Argelia".split("\\|")) ;
        areas.add("f-ao|Angola|Angola".split("\\|")) ;
        areas.add("f-bd|Burundi|Burundi".split("\\|")) ;
        areas.add("f-bs|Botswana|Botsuana".split("\\|")) ;
        areas.add("f-cd|Chad|Chad".split("\\|")) ;
        areas.add("f-cf|Congo (Brazzaville)|Congo (Brazzaville)".split("\\|")) ;
        areas.add("f-cg|Congo (Democratic Republic)|Congo (República Democrática)".split("\\|")) ;
        areas.add("f-cm|Cameroon|Camerún".split("\\|")) ;
        areas.add("f-cx|Central African Republic|República Centroafricana".split("\\|")) ;
        areas.add("f-dm|Benin|Benin".split("\\|")) ;
        areas.add("f-ea|Eritrea|Eritrea".split("\\|")) ;
        areas.add("f-eg|Equatorial Guinea|Guinea Ecuatorial".split("\\|")) ;
        areas.add("f-et|Ethiopia|Etiopía".split("\\|")) ;
        areas.add("f-ft|Djibouti|Djibouti".split("\\|")) ;
        areas.add("f-gh|Ghana|Ghana".split("\\|")) ;
        areas.add("f-gm|Gambia|Gambia".split("\\|")) ;
        areas.add("f-go|Gabon|Gabón".split("\\|")) ;
        areas.add("f-gv|Guinea|Guinea".split("\\|")) ;
        areas.add("f-iv|Côte d'Ivoire|Costa de Marfil".split("\\|")) ;
        areas.add("f-ke|Kenya|Kenia".split("\\|")) ;
        areas.add("f-lb|Liberia|Liberia".split("\\|")) ;
        areas.add("f-lo|Lesotho|Lesoto".split("\\|")) ;
        areas.add("f-ly|Libya|Libia".split("\\|")) ;
        areas.add("f-mg|Madagascar|Madagascar".split("\\|")) ;
        areas.add("f-ml|Mali|Mali".split("\\|")) ;
        areas.add("f-mr|Morocco|Marruecos".split("\\|")) ;
        areas.add("f-mu|Mauritania|Mauritania".split("\\|")) ;
        areas.add("f-mw|Malawi|Malawi".split("\\|")) ;
        areas.add("f-mz|Mozambique|Mozambique".split("\\|")) ;
        areas.add("f-ng|Niger|Níger".split("\\|")) ;
        areas.add("f-nr|Nigeria|Nigeria".split("\\|")) ;
        areas.add("f-pg|Guinea-Bissau|Guinea-Bissau".split("\\|")) ;
        areas.add("f-rh|Zimbabwe|Zimbabue".split("\\|")) ;
        areas.add("f-rw|Rwanda|Ruanda".split("\\|")) ;
        areas.add("f-sa|South Africa|Sudáfrica".split("\\|")) ;
        areas.add("f-sd|South Sudan|Sudán del Sur".split("\\|")) ;
        areas.add("f-sf|Sao Tome and Principe|Santo Tomé y Príncipe".split("\\|")) ;
        areas.add("f-sg|Senegal|Senegal".split("\\|")) ;
        areas.add("f-sh|Spanish North Africa|África del norte española".split("\\|")) ;
        areas.add("f-sj|Sudan|Sudán".split("\\|")) ;
        areas.add("f-sl|Sierra Leone|Sierra Leona".split("\\|")) ;
        areas.add("f-so|Somalia|Somalia".split("\\|")) ;
        areas.add("f-sq|Eswatini|Eswatini".split("\\|")) ;
        areas.add("f-ss|Western Sahara|Sahara Occidental".split("\\|")) ;
        areas.add("f-sx|Namibia|Namibia".split("\\|")) ;
        areas.add("f-tg|Togo|Togo".split("\\|")) ;
        areas.add("f-ti|Tunisia|Túnez".split("\\|")) ;
        areas.add("f-tz|Tanzania|Tanzania".split("\\|")) ;
        areas.add("f-ua|Egypt|Egipto".split("\\|")) ;
        areas.add("f-ug|Uganda|Uganda".split("\\|")) ;
        areas.add("f-uv|Burkina Faso|Burkina Faso".split("\\|")) ;
        areas.add("f-za|Zambia|Zambia".split("\\|")) ;
        areas.add("fa|Atlas Mountains|Montañas Atlas".split("\\|")) ;
        areas.add("fb|Africa, Sub-Saharan|África subsahariana".split("\\|")) ;
        areas.add("fc|Africa, Central|África central".split("\\|")) ;
        areas.add("fd|Sahara|Sáhara".split("\\|")) ;
        areas.add("fe|Africa, Eastern|África oriental".split("\\|")) ;
        areas.add("ff|Africa, North|África del norte".split("\\|")) ;
        areas.add("fg|Congo River|Río Congo".split("\\|")) ;
        areas.add("fh|Africa, Northeast|África, noreste".split("\\|")) ;
        areas.add("fi|Niger River|Río Níger".split("\\|")) ;
        areas.add("fl|Nile River|Rio Nilo".split("\\|")) ;
        areas.add("fn|Sudan (Region)|Sudán (región)".split("\\|")) ;
        areas.add("fq|Africa, French-speaking Equatorial|África, ecuatorial francófono".split("\\|")) ;
        areas.add("fr|Great Rift Valley|Valle Great Rift ".split("\\|")) ;
        areas.add("fs|Africa, Southern|África del sur".split("\\|")) ;
        areas.add("fu|Suez Canal (Egypt)|Canal de Suez (Egipto)".split("\\|")) ;
        areas.add("fv|Volta River (Ghana)|Río Volta (Ghana)".split("\\|")) ;
        areas.add("fw|Africa, West|África occidental".split("\\|")) ;
        areas.add("fz|Zambezi River|Río Zambezi".split("\\|")) ;
        areas.add("h|French Community|Comunidad francesa".split("\\|")) ;
        areas.add("i|Indian Ocean|Océano Indio".split("\\|")) ;
        areas.add("i-bi|British Indian Ocean Territory|Territorio Británico del Océano Índico".split("\\|")) ;
        areas.add("i-cq|Comoros|Comoras".split("\\|")) ;
        areas.add("i-fs|Terres australes et antarctiques françaises|Tierras australes y antárticas francesas".split("\\|")) ;
        areas.add("i-hm|Heard and McDonald Islands|Islas Heard y McDonald".split("\\|")) ;
        areas.add("i-mf|Mauritius|Mauricio".split("\\|")) ;
        areas.add("i-my|Mayotte|Mayotte".split("\\|")) ;
        areas.add("i-re|Réunion|Reunión".split("\\|")) ;
        areas.add("i-se|Seychelles|Seychelles".split("\\|")) ;
        areas.add("i-xa|Christmas Island (Indian Ocean)|Isla Christmas (Océano Índico)".split("\\|")) ;
        areas.add("i-xb|Cocos (Keeling) Islands|Islas Cocos (Keeling)".split("\\|")) ;
        areas.add("i-xc|Maldives|Maldivas".split("\\|")) ;
        areas.add("l|Atlantic Ocean|Océano Atlántico".split("\\|")) ;
        areas.add("ln|North Atlantic Ocean|Océano Atlántico Norte".split("\\|")) ;
        areas.add("lnaz|Azores|Azores".split("\\|")) ;
        areas.add("lnbm|Bermuda Islands|Islas Bermudas".split("\\|")) ;
        areas.add("lnca|Canary Islands|Islas Canarias".split("\\|")) ;
        areas.add("lncv|Cabo Verde|Cabo Verde".split("\\|")) ;
        areas.add("lnfa|Faroe Islands|Islas Faroe".split("\\|")) ;
        areas.add("lnjn|Jan Mayen Island|Isla Jan Mayen".split("\\|")) ;
        areas.add("lnma|Madeira Islands|Islas Madeira".split("\\|")) ;
        areas.add("lnsb|Svalbard (Norway)|Svalbard (Noruega)".split("\\|")) ;
        areas.add("ls|South Atlantic Ocean|Océano Atlántico Sur".split("\\|")) ;
        areas.add("lsai|Ascension Island (Atlantic Ocean)|Isla Ascensión (Océano Atlántico)".split("\\|")) ;
        areas.add("lsbv|Bouvet Island|Isla Bouvet".split("\\|")) ;
        areas.add("lsfk|Falkland Islands|Islas Malvinas".split("\\|")) ;
        areas.add("lstd|Tristan da Cunha|Tristan da Cunha".split("\\|")) ;
        areas.add("lsxj|Saint Helena|Santa Elena".split("\\|")) ;
        areas.add("lsxs|South Georgia and South Sandwich Islands|Islas Georgia del Sur y Sandwich del Sur".split("\\|")) ;
        areas.add("m|Intercontinental areas (Eastern Hemisphere)|Áreas intercontinentales (hemisferio oriental)".split("\\|")) ;
        areas.add("ma|Arab countries|Países árabes".split("\\|")) ;
        areas.add("mb|Black Sea|Mar Negro".split("\\|")) ;
        areas.add("me|Eurasia|Eurasia".split("\\|")) ;
        areas.add("mm|Mediterranean Region; Mediterranean Sea|Región mediterranea; mar Mediterráneo".split("\\|")) ;
        areas.add("mr|Red Sea|Mar Rojo".split("\\|")) ;
        areas.add("n|North America|Norteamérica".split("\\|")) ;
        areas.add("n-cn|Canada|Canadá".split("\\|")) ;
        areas.add("n-cn-ab|Alberta|Alberta".split("\\|")) ;
        areas.add("n-cn-bc|British Columbia|Columbia Británica".split("\\|")) ;
        areas.add("n-cn-mb|Manitoba|Manitoba".split("\\|")) ;
        areas.add("n-cn-nf|Newfoundland and Labrador|Newfoundland y Labrador".split("\\|")) ;
        areas.add("n-cn-nk|New Brunswick|Nuevo Brunswick".split("\\|")) ;
        areas.add("n-cn-ns|Nova Scotia|Nueva Escocia".split("\\|")) ;
        areas.add("n-cn-nt|Northwest Territories|Territorios del Noroeste".split("\\|")) ;
        areas.add("n-cn-nu|Nunavut|Nunavut".split("\\|")) ;
        areas.add("n-cn-on|Ontario|Ontario".split("\\|")) ;
        areas.add("n-cn-pi|Prince Edward Island|Isla Príncipe Eduardo".split("\\|")) ;
        areas.add("n-cn-qu|Québec (Province)|Québec (provincia)".split("\\|")) ;
        areas.add("n-cn-sn|Saskatchewan|Saskatchewan".split("\\|")) ;
        areas.add("n-cn-yk|Yukon Territory|Territorio de Yukon".split("\\|")) ;
        areas.add("n-cnh|Hudson Bay|Bahía Hudson".split("\\|")) ;
        areas.add("n-cnm|Maritime Provinces|Provincias Maritimas".split("\\|")) ;
        areas.add("n-cnp|Prairie Provinces|Provincias de la pradera".split("\\|")) ;
        areas.add("n-gl|Greenland|Tierra Verde".split("\\|")) ;
        areas.add("n-mx|Mexico|México".split("\\|")) ;
        areas.add("n-us|United States|Estados Unidos".split("\\|")) ;
        areas.add("n-us-ak|Alaska|Alaska".split("\\|")) ;
        areas.add("n-us-al|Alabama|Alabama".split("\\|")) ;
        areas.add("n-us-ar|Arkansas|Arkansas".split("\\|")) ;
        areas.add("n-us-az|Arizona|Arizona".split("\\|")) ;
        areas.add("n-us-ca|California|California".split("\\|")) ;
        areas.add("n-us-co|Colorado|Colorado".split("\\|")) ;
        areas.add("n-us-ct|Connecticut|Connecticut".split("\\|")) ;
        areas.add("n-us-dc|Washington (D.C.)|Washington (D.C.)".split("\\|")) ;
        areas.add("n-us-de|Delaware|Delaware".split("\\|")) ;
        areas.add("n-us-fl|Florida|Florida".split("\\|")) ;
        areas.add("n-us-ga|Georgia|Georgia".split("\\|")) ;
        areas.add("n-us-hi|Hawaii|Hawai".split("\\|")) ;
        areas.add("n-us-ia|Iowa|Iowa".split("\\|")) ;
        areas.add("n-us-id|Idaho|Idaho".split("\\|")) ;
        areas.add("n-us-il|Illinois|Illinois".split("\\|")) ;
        areas.add("n-us-in|Indiana|Indiana".split("\\|")) ;
        areas.add("n-us-ks|Kansas|Kansas".split("\\|")) ;
        areas.add("n-us-ky|Kentucky|Kentucky".split("\\|")) ;
        areas.add("n-us-la|Louisiana|Luisiana".split("\\|")) ;
        areas.add("n-us-ma|Massachusetts|Massachusetts".split("\\|")) ;
        areas.add("n-us-md|Maryland|Maryland".split("\\|")) ;
        areas.add("n-us-me|Maine|Maine".split("\\|")) ;
        areas.add("n-us-mi|Michigan|Michigan".split("\\|")) ;
        areas.add("n-us-mn|Minnesota|Minnesota".split("\\|")) ;
        areas.add("n-us-mo|Missouri|Misuri".split("\\|")) ;
        areas.add("n-us-ms|Mississippi|Misisipí".split("\\|")) ;
        areas.add("n-us-mt|Montana|Montana".split("\\|")) ;
        areas.add("n-us-nb|Nebraska|Nebraska".split("\\|")) ;
        areas.add("n-us-nc|North Carolina|Carolina del Norte".split("\\|")) ;
        areas.add("n-us-nd|North Dakota|Dakota del Norte".split("\\|")) ;
        areas.add("n-us-nh|New Hampshire|Nuevo Hampshire".split("\\|")) ;
        areas.add("n-us-nj|New Jersey|New Jersey".split("\\|")) ;
        areas.add("n-us-nm|New Mexico|Nuevo Mexico".split("\\|")) ;
        areas.add("n-us-nv|Nevada|Nevada".split("\\|")) ;
        areas.add("n-us-ny|New York|Nueva York".split("\\|")) ;
        areas.add("n-us-oh|Ohio|Ohio".split("\\|")) ;
        areas.add("n-us-ok|Oklahoma|Oklahoma".split("\\|")) ;
        areas.add("n-us-or|Oregon|Oregón".split("\\|")) ;
        areas.add("n-us-pa|Pennsylvania|Pensilvania".split("\\|")) ;
        areas.add("n-us-ri|Rhode Island|Rhode Island".split("\\|")) ;
        areas.add("n-us-sc|South Carolina|Carolina del Sur".split("\\|")) ;
        areas.add("n-us-sd|South Dakota|Dakota del Sur".split("\\|")) ;
        areas.add("n-us-tn|Tennessee|Tennesse".split("\\|")) ;
        areas.add("n-us-tx|Texas|Texas".split("\\|")) ;
        areas.add("n-us-ut|Utah|Utah".split("\\|")) ;
        areas.add("n-us-va|Virginia|Virginia".split("\\|")) ;
        areas.add("n-us-vt|Vermont|Vermont".split("\\|")) ;
        areas.add("n-us-wa|Washington (State)|Washington (estado)".split("\\|")) ;
        areas.add("n-us-wi|Wisconsin|Wisconsin".split("\\|")) ;
        areas.add("n-us-wv|West Virginia|Virginia del Oeste".split("\\|")) ;
        areas.add("n-us-wy|Wyoming|Wyoming".split("\\|")) ;
        areas.add("n-usa|Appalachian Mountains|Montañas Apalaches".split("\\|")) ;
        areas.add("n-usc|Middle West|Medio Oeste".split("\\|")) ;
        areas.add("n-use|Northeastern States|Estados del noreste".split("\\|")) ;
        areas.add("n-usl|Middle Atlantic States|Estados del Atlántico medio".split("\\|")) ;
        areas.add("n-usm|Mississippi River|Río Mississippi".split("\\|")) ;
        areas.add("n-usn|New England|Nueva Inglaterra".split("\\|")) ;
        areas.add("n-uso|Ohio River|Río de Ohio".split("\\|")) ;
        areas.add("n-usp|West (U.S.)|Oeste (EE. UU.)".split("\\|")) ;
        areas.add("n-usr|East (U.S.)|Este (EE. UU.)".split("\\|")) ;
        areas.add("n-uss|Missouri River|Río Missouri".split("\\|")) ;
        areas.add("n-ust|Southwest, New|Suroeste, nuevo".split("\\|")) ;
        areas.add("n-usu|Southern States|Estados sureños".split("\\|")) ;
        areas.add("n-xl|Saint Pierre and Miquelon|San Pedro y Miquelón".split("\\|")) ;
        areas.add("nc|Central America|Centroamérica".split("\\|")) ;
        areas.add("ncbh|Belize|Belice".split("\\|")) ;
        areas.add("nccr|Costa Rica|Costa Rica".split("\\|")) ;
        areas.add("nccz|Canal Zone|Zona del canal".split("\\|")) ;
        areas.add("nces|El Salvador|El Salvador".split("\\|")) ;
        areas.add("ncgt|Guatemala|Guatemala".split("\\|")) ;
        areas.add("ncho|Honduras|Honduras".split("\\|")) ;
        areas.add("ncnq|Nicaragua|Nicaragua".split("\\|")) ;
        areas.add("ncpn|Panama|Panamá".split("\\|")) ;
        areas.add("nl|Great Lakes (North America); Lake States|Grandes Lagos (América del Norte); Estados del lago".split("\\|")) ;
        areas.add("nm|Mexico, Gulf of|Golfo de México".split("\\|")) ;
        areas.add("np|Great Plains|Grandes llanuras".split("\\|")) ;
        areas.add("nr|Rocky Mountains|Montañas Rocosas".split("\\|")) ;
        areas.add("nw|West Indies|Antillas".split("\\|")) ;
        areas.add("nwaq|Antigua and Barbuda|Antigua y Barbuda".split("\\|")) ;
        areas.add("nwaw|Aruba|Aruba".split("\\|")) ;
        areas.add("nwbb|Barbados|Barbados".split("\\|")) ;
        areas.add("nwbf|Bahamas|Bahamas".split("\\|")) ;
        areas.add("nwbn|Bonaire|Bonaire".split("\\|")) ;
        areas.add("nwcj|Cayman Islands|Islas Caimán".split("\\|")) ;
        areas.add("nwco|Curaçao|Curaçao".split("\\|")) ;
        areas.add("nwcu|Cuba|Cuba".split("\\|")) ;
        areas.add("nwdq|Dominica|Dominica".split("\\|")) ;
        areas.add("nwdr|Dominican Republic|República Dominicana".split("\\|")) ;
        areas.add("nweu|Sint Eustatius|San Eustaquio".split("\\|")) ;
        areas.add("nwgd|Grenada|Granada".split("\\|")) ;
        areas.add("nwgp|Guadeloupe|Guadalupe".split("\\|")) ;
        areas.add("nwhi|Hispaniola|La Española".split("\\|")) ;
        areas.add("nwht|Haiti|Haití".split("\\|")) ;
        areas.add("nwjm|Jamaica|Jamaica".split("\\|")) ;
        areas.add("nwla|Antilles, Lesser|Antillas Menores".split("\\|")) ;
        areas.add("nwli|Leeward Islands (West Indies)|Islas de Sotavento (Antillas)".split("\\|")) ;
        areas.add("nwmj|Montserrat|Montserrat".split("\\|")) ;
        areas.add("nwmq|Martinique|Martinica".split("\\|")) ;
        areas.add("nwpr|Puerto Rico|Puerto Rico".split("\\|")) ;
        areas.add("nwsc|Saint-Barthélemy|San Bartolomé".split("\\|")) ;
        areas.add("nwsd|Saba|Saba".split("\\|")) ;
        areas.add("nwsn|Sint Maarten|Sint Maarten".split("\\|")) ;
        areas.add("nwst|Saint-Martin|San Martín".split("\\|")) ;
        areas.add("nwsv|Swan Islands (Honduras)|Islas Swan (Honduras)".split("\\|")) ;
        areas.add("nwtc|Turks and Caicos Islands|Islas Turcas y Caicos".split("\\|")) ;
        areas.add("nwtr|Trinidad and Tobago|Trinidad y Tobago".split("\\|")) ;
        areas.add("nwuc|United States Miscellaneous Caribbean Islands|Estados Unidos, varias Islas del Caribe".split("\\|")) ;
        areas.add("nwvb|British Virgin Islands|Islas Vírgenes Británicas".split("\\|")) ;
        areas.add("nwvi|Virgin Islands of the United States|Islas Vírgenes de los Estados Unidos".split("\\|")) ;
        areas.add("nwwi|Windward Islands (West Indies)|Islas de Barlovento (Antillas)".split("\\|")) ;
        areas.add("nwxa|Anguilla|Anguila".split("\\|")) ;
        areas.add("nwxi|Saint Kitts and Nevis|San Cristóbal y Nieves".split("\\|")) ;
        areas.add("nwxk|Saint Lucia|Santa Lucía".split("\\|")) ;
        areas.add("nwxm|Saint Vincent and the Grenadines|San Vicente y las Granadinas".split("\\|")) ;
        areas.add("p|Pacific Ocean|Océano Pacífico".split("\\|")) ;
        areas.add("pn|North Pacific Ocean|Océano Pacífico Norte".split("\\|")) ;
        areas.add("po|Oceania|Oceanía".split("\\|")) ;
        areas.add("poas|American Samoa|Samoa Americana".split("\\|")) ;
        areas.add("pobp|Solomon Islands|Islas Salomón".split("\\|")) ;
        areas.add("poci|Caroline Islands|Islas Caroline".split("\\|")) ;
        areas.add("pocw|Cook Islands|Islas Cook".split("\\|")) ;
        areas.add("poea|Easter Island|isla de Pascua".split("\\|")) ;
        areas.add("pofj|Fiji|Fiyi".split("\\|")) ;
        areas.add("pofp|French Polynesia|Polinesia francesa".split("\\|")) ;
        areas.add("pogg|Galapagos Islands|Islas Galápagos".split("\\|")) ;
        areas.add("pogu|Guam|Guam".split("\\|")) ;
        areas.add("poji|Johnston Island|Isla Johnston".split("\\|")) ;
        areas.add("pokb|Kiribati|Kiribati".split("\\|")) ;
        areas.add("poki|Kermadec Islands|Islas Kermadec".split("\\|")) ;
        areas.add("poln|Line Islands|Islas Line".split("\\|")) ;
        areas.add("pome|Melanesia|Melanesia".split("\\|")) ;
        areas.add("pomi|Micronesia (Federated States)|Micronesia (Estados Federados)".split("\\|")) ;
        areas.add("ponl|New Caledonia|Nueva Caledonia".split("\\|")) ;
        areas.add("ponn|Vanuatu|Vanuatu".split("\\|")) ;
        areas.add("ponu|Nauru|Nauru".split("\\|")) ;
        areas.add("popc|Pitcairn Island|Isla Pitcairn".split("\\|")) ;
        areas.add("popl|Palau|Palau".split("\\|")) ;
        areas.add("pops|Polynesia|Polinesia".split("\\|")) ;
        areas.add("posh|Samoan Islands|Islas samoanas".split("\\|")) ;
        areas.add("potl|Tokelau|Tokelau".split("\\|")) ;
        areas.add("poto|Tonga|Tonga".split("\\|")) ;
        areas.add("pott|Micronesia|Micronesia".split("\\|")) ;
        areas.add("potv|Tuvalu|Tuvalu".split("\\|")) ;
        areas.add("poup|United States Miscellaneous Pacific Islands|Estados Unidos, varias islas del Pacífico".split("\\|")) ;
        areas.add("powf|Wallis and Futuna Islands|Islas Wallis y Futuna".split("\\|")) ;
        areas.add("powk|Wake Island|Isla Wake".split("\\|")) ;
        areas.add("pows|Samoa|Samoa".split("\\|")) ;
        areas.add("poxd|Mariana Islands|Islas Mariana".split("\\|")) ;
        areas.add("poxe|Marshall Islands|Islas Marshall".split("\\|")) ;
        areas.add("poxf|Midway Islands|Islas Midway".split("\\|")) ;
        areas.add("poxh|Niue|Niue".split("\\|")) ;
        areas.add("ps|South Pacific Ocean|Oceano Pacifico del Sur".split("\\|")) ;
        areas.add("q|Cold regions|Regiones frías".split("\\|")) ;
        areas.add("r|Arctic Ocean; Arctic regions|Océano Ártico; Regiones árticas".split("\\|")) ;
        areas.add("s|South America|Sudamerica".split("\\|")) ;
        areas.add("s-ag|Argentina|Argentina".split("\\|")) ;
        areas.add("s-bl|Brazil|Brasil".split("\\|")) ;
        areas.add("s-bo|Bolivia|Bolivia".split("\\|")) ;
        areas.add("s-ck|Colombia|Colombia".split("\\|")) ;
        areas.add("s-cl|Chile|Chile".split("\\|")) ;
        areas.add("s-ec|Ecuador|Ecuador".split("\\|")) ;
        areas.add("s-fg|French Guiana|Guayana Francesa".split("\\|")) ;
        areas.add("s-gy|Guyana|Guayana".split("\\|")) ;
        areas.add("s-pe|Peru|Perú".split("\\|")) ;
        areas.add("s-py|Paraguay|Paraguay".split("\\|")) ;
        areas.add("s-sr|Suriname|Surinam".split("\\|")) ;
        areas.add("s-uy|Uruguay|Uruguay".split("\\|")) ;
        areas.add("s-ve|Venezuela|Venezuela".split("\\|")) ;
        areas.add("sa|Amazon River|Río Amazonas".split("\\|")) ;
        areas.add("sn|Andes|Andes".split("\\|")) ;
        areas.add("sp|Rio de la Plata (Argentina and Uruguay)|Rio de la Plata (Argentina y Uruguay)".split("\\|")) ;
        areas.add("t|Antarctic Ocean; Antarctica|Oceano Antártico; Antártida".split("\\|")) ;
        areas.add("u|Australasia|Australasia".split("\\|")) ;
        areas.add("u-ac|Ashmore and Cartier Islands|Islas Ashmore y Cartier".split("\\|")) ;
        areas.add("u-at|Australia|Australia".split("\\|")) ;
        areas.add("u-at-ac|Australian Capital Territory|Territorio de la capital australiana".split("\\|")) ;
        areas.add("u-atc|Central Australia|Australia central".split("\\|")) ;
        areas.add("u-ate|Eastern Australia|Australia del este".split("\\|")) ;
        areas.add("u-atn|Northern Australia|Norte de Australia".split("\\|")) ;
        areas.add("u-at-ne|New South Wales|Nueva Gales del Sur".split("\\|")) ;
        areas.add("u-at-no|Northern Territory|Territorio del Norte".split("\\|")) ;
        areas.add("u-at-qn|Queensland|Queensland".split("\\|")) ;
        areas.add("u-at-sa|South Australia|Sur de Australia".split("\\|")) ;
        areas.add("u-at-tm|Tasmania|Tasmania".split("\\|")) ;
        areas.add("u-at-vi|Victoria|Victoria".split("\\|")) ;
        areas.add("u-at-we|Western Australia|Oeste de Australia".split("\\|")) ;
        areas.add("u-cs|Coral Sea Islands|Islas Coral Sea".split("\\|")) ;
        areas.add("u-nz|New Zealand|Nueva Zelanda".split("\\|")) ;
        areas.add("w|Tropics|Trópicos".split("\\|")) ;
        areas.add("x|Earth|Tierra".split("\\|")) ;
        areas.add("xa|Eastern Hemisphere|Hemisferio Este".split("\\|")) ;
        areas.add("xb|Northern Hemisphere|Hemisferio Norte".split("\\|")) ;
        areas.add("xc|Southern Hemisphere|Hemisferio Sur".split("\\|")) ;
        areas.add("xd|Western Hemisphere|Hemisferio Oeste".split("\\|")) ;
        areas.add("zd|Deep space|Espacio profundo".split("\\|")) ;
        areas.add("zju|Jupiter|Júpiter".split("\\|")) ;
        areas.add("zma|Mars|Marte".split("\\|")) ;
        areas.add("zme|Mercury|Mercurio".split("\\|")) ;
        areas.add("zmo|Moon|Luna".split("\\|")) ;
        areas.add("zne|Neptune|Neptuno".split("\\|")) ;
        areas.add("zo|Outer space|Espacio exterior".split("\\|")) ;
        areas.add("zpl|Pluto|Plutón".split("\\|")) ;
        areas.add("zs|Solar system|Sistema solar".split("\\|")) ;
        areas.add("zsa|Saturn|Saturno".split("\\|")) ;
        areas.add("zsu|Sun|Sol".split("\\|")) ;
        areas.add("zur|Uranus|Urano".split("\\|")) ;
        areas.add("zve|Venus|Venus".split("\\|")) ;
        return areas ;
    }
    
}
